### PR TITLE
Error in line 14

### PR DESCRIPTION
**Pull request by druelle-mobile**
Modified : line 14 <style name="Widget.Shrine.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlineBox">
to <style name="Widget.Shrine.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">

### CODE REVIEW

**Comment by druelle-mobile** [comment]
@googlebot I signed the CLA ! 😸

**Comment by cketcham** [comment]
It's true, we have changed this in the latest release, but the version of the library that is used in the example is using the `OutlineBox` style rather than the `OutlinedBox` style. Did you test this change without updating the library?

**Comment by druelle-mobile** [comment]
I just test and it failed.
image

So I don't remember but the lib has been upgraded in my pull request.

**Comment by cketcham** [comment]
I only get this error when I update to the `com.android.support:design:28.0.0-alpha3` dependency which we haven't done for the codelabs yet. I'm going to close this pr for now since it is working without the update.

**Pull request closed without merging**
